### ISSUE TITLE
Pressing almost any key crashes the program

### ISSUE THREAD

**Issue by FedericoStra** [Lauriat/texel#1]
As the title says, pressing any key apart from `Tab`, `Shift-Tab`, `h`/`j`/`k`/`l`, arrows, `c`/`y`, `v`, `q` crashes the application:
```
Traceback (most recent call last):
  File "/home/.../.local/bin/texel", line 8, in <module>
    sys.exit(main())
  File "/home/.../.local/lib/python3.10/site-packages/texel/texel.py", line 66, in main
    curses.wrapper(run, sheets, args)
  File "/usr/lib64/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/.../.local/lib/python3.10/site-packages/texel/texel.py", line 17, in run
    while grid.handle_press(scr.getch()):
  File "/home/.../.local/lib/python3.10/site-packages/texel/grid.py", line 46, in handle_press
    elif key == Keys.QUIT:
  File "/home/.../.local/lib/python3.10/site-packages/texel/keys.py", line 11, in __eq__
    return self._hash == other._hash
AttributeError: 'NoneType' object has no attribute '_hash'
```

It would be better to do nothing or write "command not supported in a status line", and maybe implement the command `?` that summarizes the available keybindings.

**Comment by Lauriat** [comment]
Thanks for opening an issue! Fixed the crash in ee989f1

Will look into adding `?` command at some point.
