### ISSUE TITLE
open xls file fail

### ISSUE THREAD

**Issue by ruizgo** [Lauriat/texel#2]
Traceback (most recent call last):
  File "/home/.../.local/bin/texel", line 8, in <module>
    sys.exit(main())
  File "/home/.../.local/lib/python3.6/site-packages/texel/texel.py", line 66, in main
    curses.wrapper(run, sheets, args)
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/.../.local/lib/python3.6/site-packages/texel/texel.py", line 15, in run
    Styles(args.cellwidth, args.precision),
  File "/home/.../.local/lib/python3.6/site-packages/texel/styles.py", line 20, in __init__
    self.init_colors()
  File "/home/.../.local/lib/python3.6/site-packages/texel/styles.py", line 37, in init_colors
    curses.init_pair(6, C.LIGHT_MAGENTA, C.BLACK)
_curses.error: init_pair() returned ERR

**Comment by Lauriat** [comment]
What is your `TERM`?
Setting `export TERM=xterm-256color` might help.

**Comment by ruizgo** [comment]
good! thks
