### ISSUE TITLE
moving around in header can crash app

### ISSUE THREAD

**Issue by theconsultant** [Lauriat/texel#3]
When I use the keyboard to move quickly past the left edge of the screen in the Header column or moving to the right only a few cells, also in the header, can crash the app.

Awesome app. Thanks!

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/texel", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/texel/texel.py", line 66, in main
    curses.wrapper(run, sheets, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/texel/texel.py", line 17, in run
    while grid.handle_press(scr.getch()):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/texel/grid.py", line 45, in handle_press
    self.actions[key]()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/texel/grid.py", line 38, in runnable
    self.draw()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/texel/grid.py", line 175, in draw
    self.draw_footer()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/texel/grid.py", line 163, in draw_footer
    self.scr.addstr(
_curses.error: addwstr() returned ERR

**Comment by Lauriat** [comment]
Thanks!
Hmm.. I was able to replicate the error when the cell value was longer than the width of the screen. Not sure if that was it in your case?  Anyways fixed it  in 9ca1a6e and uploaded a new version to pypi.

**Comment by theconsultant** [comment]
It might have been that, as some of the headers had a whole paragraph in them.

Either way, I did a `pip install --upgrade texel` and it all works now. :-)
